import type { Analysis } from "../contracts";
import type { Workspace } from "../workspace";

/**
 * BP-06 — scaffold framework standar (PRD).
 * Idempoten: file yang sudah ada tidak ditimpa, hanya dilengkapi bila hilang.
 */
export function scaffoldFramework(ws: Workspace, analysis: Analysis, root = "autoqa") {
  const base = analysis.stack.frameworks.includes("nextjs") ? "src" : ".";
  const files: Record<string, string> = {
    [`${root}/playwright.config.ts`]: `import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  retries: process.env.CI ? 2 : 0,
  forbidOnly: !!process.env.CI,
  reporter: [["blob"], ["html", { open: "never" }]],
  use: {
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    testIdAttribute: "data-testid",
  },
  projects: [
    { name: "chromium", use: { ...devices["Desktop Chrome"] } },
  ],
});
`,
    [`${root}/fixtures/index.ts`]: `import { test as base } from "@playwright/test";

export const test = base.extend<{ authToken: string }>({
  authToken: async ({}, use, workerInfo) => {
    const res = await fetch(\`\${process.env.API_BASE_URL}/api/test/token\`, {
      method: "POST",
      body: JSON.stringify({ worker: workerInfo.workerIndex }),
    });
    await use(((await res.json()) as { token: string }).token);
  },
});
export { expect } from "@playwright/test";
`,
    [`${root}/config/env.ts`]: `import { z } from "zod";

export const env = z.object({
  BASE_URL: z.string().url(),
  API_BASE_URL: z.string().url(),
  API_TOKEN: z.string().optional(),
}).parse({
  BASE_URL: process.env.BASE_URL,
  API_BASE_URL: process.env.API_BASE_URL,
  API_TOKEN: process.env.API_TOKEN,
});
`,
    [`${root}/utils/waits.ts`]: `import { expect, type Locator, type Page } from "@playwright/test";

/** Wait berbasis event — dilarang memakai waitForTimeout (kebijakan quality gate). */
export async function waitForStable(page: Page) {
  await page.waitForLoadState("networkidle");
}

export async function expectVisible(locator: Locator) {
  await expect(locator).toBeVisible({ timeout: 10_000 });
}
`,
    [`${root}/pages/api/client.ts`]: `import { APIRequestContext, request } from "@playwright/test";

export class ApiClient {
  constructor(private ctx: APIRequestContext) {}

  static async create(baseURL: string, token?: string) {
    return new ApiClient(await request.newContext({
      baseURL,
      extraHTTPHeaders: token ? { Authorization: \`Bearer \${token}\` } : {},
    }));
  }

  get<T>(path: string) {
    return this.ctx.get<T>(path);
  }

  post<T>(path: string, data: unknown) {
    return this.ctx.post<T>(path, { data });
  }
}
`,
    [`${root}/.github/copilot-instructions.md`]: `# AutoQA testing conventions

- Gunakan \`getByRole\` atau \`getByTestId\`. Dilarang XPath/CSS absolut.
- Dilarang \`waitForTimeout\`.
- Setiap test wajib bertag (\`@smoke\`, \`@api\`, \`@ui\`, \`@e2e\`).
- Setiap test wajib punya anotasi cakupan:
  \`test.info().annotations.push({ type: "covers", description: "api:POST /orders" })\`.
- Satu assertion utama per test concept.
- Jangan pernah melemahkan assertion agar test lulus.
`,
    [`${root}/package.json`]: `{
  "name": "autoqa-suite",
  "private": true,
  "scripts": {
    "test": "playwright test",
    "test:api": "playwright test tests/api",
    "test:ui": "playwright test tests/ui",
    "report": "playwright show-report"
  },
  "devDependencies": { "@playwright/test": "1.49.0" }
}
`,
    [`${root}/README.md`]: `# Generated by Veriflow

Otomatis dibuat pada run ${"" /* diisi engine */}. Struktur: tests/ui, tests/api, tests/e2e, pages, fixtures, utils.
`,
  };

  const created: string[] = [];
  const skipped: string[] = [];
  for (const [path, content] of Object.entries(files)) {
    if (ws.files[path]) { skipped.push(path); continue; }
    ws.files[path] = content;
    created.push(path);
  }
  void base;
  return { root, created, skipped, total: Object.keys(files).length };
}